baseURL = 'https://jucaaquino.com/'
languageCode = 'en-us'
title = 'Juca Aquino'
pluralizelisttitles = false
[menu]
    [[menu.main]]
        name = 'Work'
        url = '/work/'
        weight = 1
    [[menu.main]]
        name = 'About'
        url = '/about/'
        weight = 2
    [[menu.main]]
        name = 'Contact'
        url = '/contact/'
        weight = 3
